import { Icons } from "./icons";

export const planets = [
  {
    src: Icons.java,
    label: "Java",
    description: "Object-oriented programming for enterprise applications.",
    size: 48,
    orbit: 120,
    speed: 20,
    direction: "cw",
    startAngle: 0,
  },
  {
    src: Icons.spring,
    label: "Spring",
    description: "Powerful framework for building Java enterprise applications.",
    size: 42,
    orbit: 120,
    speed: 20,
    direction: "cw",
    startAngle: 150, // 150 degrees from Java
  },
  {
    src: Icons.html,
    label: "HTML",
    description: "The foundation of web pages - structure and semantic markup.",
    size: 40,
    orbit: 180,
    speed: 35,
    direction: "ccw",
    startAngle: 45,
  },
  {
    src: Icons.css,
    label: "CSS",
    description: "Styling and layout for beautiful, responsive web designs.",
    size: 36,
    orbit: 240,
    speed: 25,
    direction: "cw",
    startAngle: 0,
  },
  {
    src: Icons.tailwindcss,
    label: "Tailwind CSS",
    description: "Utility-first CSS framework for rapid UI development.",
    size: 38,
    orbit: 240,
    speed: 25,
    direction: "cw",
    startAngle: 180, // 180 degrees from CSS
  },
  {
    src: Icons.javascript,
    label: "JavaScript",
    description: "Modern web development language with comprehensive DOM manipulation and API integration.",
    size: 44,
    orbit: 300,
    speed: 40,
    direction: "ccw",
    startAngle: 60,
  },
  {
    src: Icons.react,
    label: "React",
    description: "JavaScript library for building dynamic user interfaces.",
    size: 40,
    orbit: 300,
    speed: 40,
    direction: "ccw",
    startAngle: 240, // 180 degrees from JavaScript
  },
  {
    src: Icons.git,
    label: "Git",
    description: "Version control system to track changes, collaborate, and manage code efficiently.",
    size: 32,
    orbit: 360,
    speed: 70,
    direction: "cw",
    startAngle: 90,
  },
];